languageCode = "en-us"
title = "Waking From Innocent Dreams"
tabTitle = "Instructions"
baseURL = "http://localhost:1313/"
theme = "hugo-theme-massively"
disableComments = 'true'
enableRobotsTXT= true

[menu]
  [[menu.main]]
  identifier = "about"
  name = "About The Book"
  url = "/"
  [[menu.main]]
  identifier = "help"
  name = "How You Can Help"
  url = "/how-you-can-help/"

[params]
  ## Set below parameter to define a favicon
  # favicon = "favicon.ico"
  ## Set to change date format
  # dateFormat = "2.1.2006"
  ## Set theme-color for mobile devices
  themeColor = "#000"

# Below parameters can be set to override default post settings
 [params.posts]
#     folderName = "post"
     pageSize = "14"
#     featuredPost = true
#     paginationPages = 2
#     showFirstLast = false

# [languages]
# [languages.en]
#   languageName = "English"
# [languages.es]
#   languageName = "Español"
#   title = "Massively - Versión Español"
#[languages.fr]
#  languageName = "Français"
#  title = "Massively - Version Française"