languageCode = "en-us"
tabTitle = "Instructions"
baseURL = "http://localhost:1313/"
theme = "hugo-theme-massively"
disableComments = 'true'
enableRobotsTXT= true
disableKinds = ["taxonomy", "term", "tag"]
