languageCode = "en-us"
tabTitle = "Instructions"
baseURL = "http://localhost:1313/"
theme = "hugo-theme-massively"
disableComments = 'true'
enableRobotsTXT= true
disableKinds = ["taxonomy", "term", "tag"]

[menu]
  [[menu.main]]
  identifier = "about-the-book"
  name = "About The Book"
  url = "/"
  weight = 10
  [[menu.main]]
  identifier = "news"
  name = "News"
  url = "/news/"
  weight = 20

[params]
  title = "Waking From Innocent Dreams"
  keywords = "Book, Author, Novel, Autobiographical, El Salvador"
  description = "An upcoming autobiograghical novel by Nelson/Roberto."
  ## Set below parameter to define a favicon
  # favicon = "favicon.ico"
  ## Set to change date format
  # dateFormat = "2.1.2006"
  ## Set theme-color for mobile devices
  [[params.themeColor]]
    content = "#000000"

# Below parameters can be set to override default post settings
 [params.posts]
   folderName = "features"
   pageSize = "14"
   featuredPost = true
#     featuredPost = true
#     paginationPages = 2
#     showFirstLast = false

# [languages]
# [languages.en]
#   languageName = "English"
# [languages.es]
#   languageName = "Español"
#   title = "Massively - Versión Español"
#[languages.fr]
#  languageName = "Français"
#  title = "Massively - Version Française"