[[main]]
  identifier = "about-the-book"
  name = "About The Book"
  url = "/"
  weight = 10
[[main]]
  identifier = "excerpt"
  name = "Read an Excerpt"
  url = "/excerpt/"
  weight = 15
[[main]]
  identifier = "news"
  name = "The Latest News"
  url = "/news/"
  weight = 30
[[main]]
  identifier = "outreach"
  name = "Spread the Word"
  url = "/spread-the-word/"
  weight = 20