## Open Graph Data
title = "Waking From Innocent Dreams"
keywords = "Book, Author, Novel, Autobiographical, El Salvador, Nelson/Roberto"
description = "An upcoming autobiographical novel by Nelson/Roberto."
images = ['images/wfid_cover.png', 'images/bg.png']
Copyright = "[Nelson/Roberto](https://nelsonroberto.com)"

## Set below parameter to define a favicon
# favicon = "favicon.ico"

## Set to change date format
# dateFormat = "2.1.2006"

## Set theme-color for mobile devices
[[themeColor]]
  content = "#000000"

# Below parameters can be set to override default post settings
[posts]
 folderName = "features"
 pageSize = "14"
 featuredPost = true
#     paginationPages = 2
#     showFirstLast = false