name: Hugo Build Beta Site and Deploy to S3

on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  call-reuseable-workflow:
    uses: Coto-Studio/workflows/.github/workflows/hugo-build-and-deploy-dev.yml@main
    secrets:
      obj-access-key: ${{ secrets.LINODE_ACCESS_KEY }}
      obj-secret-key: ${{ secrets.LINODE_SECRET_KEY }}
